import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import notesRouter from "./notes";
import ideasRouter from "./ideas";
import memoriesRouter from "./memories";
import resourcesRouter from "./resources";
import graphRouter from "./graph";
import chatsRouter from "./chats";
import brainRouter from "./brain";
import tasksRouter from "./tasks";
import goalsRouter from "./goals";
import habitsRouter from "./habits";
import focusRouter from "./focus";
import remindersRouter from "./reminders";
import plannerRouter from "./planner";
import reviewsRouter from "./reviews";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(notesRouter);
router.use(ideasRouter);
router.use(memoriesRouter);
router.use(resourcesRouter);
router.use(graphRouter);
router.use(chatsRouter);
router.use(brainRouter);
router.use(tasksRouter);
router.use(goalsRouter);
router.use(habitsRouter);
router.use(focusRouter);
router.use(remindersRouter);
router.use(plannerRouter);
router.use(reviewsRouter);

export default router;
