import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import notesRouter from "./notes";
import ideasRouter from "./ideas";
import memoriesRouter from "./memories";
import resourcesRouter from "./resources";
import graphRouter from "./graph";
import chatsRouter from "./chats";
import brainRouter from "./brain";
import tasksRouter from "./tasks";
import goalsRouter from "./goals";
import habitsRouter from "./habits";
import focusRouter from "./focus";
import remindersRouter from "./reminders";
import plannerRouter from "./planner";
import reviewsRouter from "./reviews";
import studyProfileRouter from "./studyProfile";
import subjectsRouter from "./subjects";
import flashcardsRouter from "./flashcards";
import quizzesRouter from "./quizzes";
import revisionRouter from "./revision";
import careerProfileRouter from "./careerProfile";
import resumesRouter from "./resumes";
import skillsRouter from "./skills";
import projectsRouter from "./projects";
import careerGoalsRouter from "./careerGoals";
import interviewRouter from "./interview";
import applicationsRouter from "./applications";
import companiesRouter from "./companies";
import lifeProfileRouter from "./lifeProfile";
import timelineRouter from "./timeline";
import insightsRouter from "./insights";
import analyticsRouter from "./analytics";
import lifeDecisionRouter from "./lifeDecision";
import aiSettingsRouter from "./aiSettings";
import automationRouter from "./automation";
import systemHealthRouter from "./systemHealth";
import aiProviderRouter from "./aiProvider";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(notesRouter);
router.use(ideasRouter);
router.use(memoriesRouter);
router.use(resourcesRouter);
router.use(graphRouter);
router.use(chatsRouter);
router.use(brainRouter);
router.use(tasksRouter);
router.use(goalsRouter);
router.use(habitsRouter);
router.use(focusRouter);
router.use(remindersRouter);
router.use(plannerRouter);
router.use(reviewsRouter);
router.use(studyProfileRouter);
router.use(subjectsRouter);
router.use(flashcardsRouter);
router.use(quizzesRouter);
router.use(revisionRouter);
router.use(careerProfileRouter);
router.use(resumesRouter);
router.use(skillsRouter);
router.use(projectsRouter);
router.use(careerGoalsRouter);
router.use(interviewRouter);
router.use(applicationsRouter);
router.use(companiesRouter);
router.use(lifeProfileRouter);
router.use(timelineRouter);
router.use(insightsRouter);
router.use(analyticsRouter);
router.use(lifeDecisionRouter);
router.use(aiSettingsRouter);
router.use(automationRouter);
router.use(systemHealthRouter);
router.use(aiProviderRouter);

export default router;
